version:  '3'
services:
  db:
    image: mysql
    ports:
        - 3306:3306
    container_name: cookezdb
    environment: 
        - MYSQL_ROOT_PASSWORD=root
    restart: always
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8000:80
    environment: 
        - PMA_HOST=cookezdb
    restart: always
    depends_on: 
        - db
  nginx:
    image: nginx
    restart: on-failure
    volumes:
        - './public:/usr/src/app'
        - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
        - '3200:80'
    depends_on: 
        - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
        - .env
    user: 1000:1000