index:
    path: /
    controller: App\Controller\HomeController::index
api_login_check:
    path: /api/login_check
    methods: ['POST']
authentication_token:
    path: /authentication_token
    methods: ['POST']