index:
    path: /
    controller: App\Controller\HomeController::index
api_login_check:
    path: /api/login_check
    methods: ['POST']
authentication_token:
    path: /authentication_token
    methods: ['POST']
    
api_recettes_ingredients:
    path: '/api/recettes_ingredients'
    methods: ['GET']
    defaults:
        _controller: '\App\Controller\ApiRoutesController::recettesByIngredients'
        _api_resource_class: 'App\Entity\Recettes'
        _api_collection_operation_name: 'collName_api_me'